# GNUmakefile - automatically generated by configure.  Do not edit.

# No suffix rules
.SUFFIXES:

# Include configuration
include Makeconfig

.PHONY:	all  lib_all
all:	 lib_all

# Include substitution rules.
include subst.rules

include lib/Makefrag

lib/%.o:	lib/%.c
	$(CC) $(CFLAGS) $(lib_CFLAGS) $(lib_DEFS) $(BASE_INCS) -Ilib $(lib_INCS) -c $< -o $@

lib/%.i:	lib/%.c
	$(CC) $(CFLAGS) $(lib_CFLAGS) $(lib_DEFS) $(BASE_INCS) -Ilib $(lib_INCS) -E $< -o $@

lib/%.s:	lib/%.c
	$(CC) $(CFLAGS) $(lib_CFLAGS) $(lib_DEFS) $(BASE_INCS) -Ilib $(lib_INCS) -S -fverbose-asm $< -o $@

lib/%.d:	lib/%.c
	./mkdep $< $@ $(CC) $(CFLAGS) $(lib_CFLAGS) $(lib_DEFS) $(BASE_INCS) -Ilib $(lib_INCS)

ifneq ($(nodep),true)
include  adventure/crc.d adventure/data.d adventure/done.d adventure/init.d adventure/io.d adventure/main.d adventure/save.d adventure/subr.d adventure/vocab.d adventure/wizard.d
endif

adventure/adventure:	 adventure/crc.o adventure/data.o adventure/done.o adventure/init.o adventure/io.o adventure/main.o adventure/save.o adventure/subr.o adventure/vocab.o adventure/wizard.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  adventure/setup.d
endif

adventure/setup:	 adventure/setup.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  arithmetic/arithmetic.d lib/getprogname.d
endif

arithmetic/arithmetic:	 arithmetic/arithmetic.o lib/getprogname.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  atc/extern.d atc/grammar.d atc/graphics.d atc/input.d atc/lex.d atc/list.d atc/log.d atc/main.d atc/tunable.d atc/update.d lib/strlcpy.d
endif

atc/atc:	 atc/extern.o atc/grammar.o atc/graphics.o atc/input.o atc/lex.o atc/list.o atc/log.o atc/main.o atc/tunable.o atc/update.o lib/strlcpy.o
	$(CC) $(LDFLAGS) $^ -lm $(NCURSES_LIB) $(LEX_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  backgammon/backgammon/extra.d backgammon/backgammon/main.d backgammon/backgammon/move.d backgammon/backgammon/text.d backgammon/backgammon/version.d backgammon/common_source/allow.d backgammon/common_source/board.d backgammon/common_source/check.d backgammon/common_source/fancy.d backgammon/common_source/init.d backgammon/common_source/odds.d backgammon/common_source/one.d backgammon/common_source/save.d backgammon/common_source/subs.d backgammon/common_source/table.d
endif

backgammon/backgammon/backgammon:	 backgammon/backgammon/extra.o backgammon/backgammon/main.o backgammon/backgammon/move.o backgammon/backgammon/text.o backgammon/backgammon/version.o backgammon/common_source/allow.o backgammon/common_source/board.o backgammon/common_source/check.o backgammon/common_source/fancy.o backgammon/common_source/init.o backgammon/common_source/odds.o backgammon/common_source/one.o backgammon/common_source/save.o backgammon/common_source/subs.o backgammon/common_source/table.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  backgammon/teachgammon/data.d backgammon/teachgammon/teach.d backgammon/teachgammon/ttext1.d backgammon/teachgammon/ttext2.d backgammon/teachgammon/tutor.d
endif

backgammon/teachgammon/teachgammon:	 backgammon/teachgammon/data.o backgammon/teachgammon/teach.o backgammon/teachgammon/ttext1.o backgammon/teachgammon/ttext2.o backgammon/teachgammon/tutor.o backgammon/common_source/allow.o backgammon/common_source/board.o backgammon/common_source/check.o backgammon/common_source/fancy.o backgammon/common_source/init.o backgammon/common_source/one.o backgammon/common_source/save.o backgammon/common_source/subs.o backgammon/common_source/table.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  battlestar/battlestar.d battlestar/command1.d battlestar/command2.d battlestar/command3.d battlestar/command4.d battlestar/command5.d battlestar/command6.d battlestar/command7.d battlestar/cypher.d battlestar/dayfile.d battlestar/dayobjs.d battlestar/fly.d battlestar/getcom.d battlestar/globals.d battlestar/init.d battlestar/misc.d battlestar/nightfile.d battlestar/nightobjs.d battlestar/parse.d battlestar/room.d battlestar/save.d battlestar/words.d lib/fgetln.d
endif

battlestar/battlestar:	 battlestar/battlestar.o battlestar/command1.o battlestar/command2.o battlestar/command3.o battlestar/command4.o battlestar/command5.o battlestar/command6.o battlestar/command7.o battlestar/cypher.o battlestar/dayfile.o battlestar/dayobjs.o battlestar/fly.o battlestar/getcom.o battlestar/globals.o battlestar/init.o battlestar/misc.o battlestar/nightfile.o battlestar/nightobjs.o battlestar/parse.o battlestar/room.o battlestar/save.o battlestar/words.o lib/fgetln.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  bcd/bcd.d
endif

bcd/bcd:	 bcd/bcd.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  boggle/boggle/bog.d boggle/boggle/help.d boggle/boggle/mach.d boggle/boggle/prtable.d boggle/boggle/timer.d boggle/boggle/word.d
endif

boggle/boggle/boggle:	 boggle/boggle/bog.o boggle/boggle/help.o boggle/boggle/mach.o boggle/boggle/prtable.o boggle/boggle/timer.o boggle/boggle/word.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  boggle/mkdict/mkdict.d
endif

boggle/mkdict/mkdict:	 boggle/mkdict/mkdict.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  boggle/mkindex/mkindex.d
endif

boggle/mkindex/mkindex:	 boggle/mkindex/mkindex.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  caesar/caesar.d
endif

caesar/caesar:	 caesar/caesar.o
	$(CC) $(LDFLAGS) $^ -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  canfield/canfield/canfield.d
endif

canfield/canfield/canfield:	 canfield/canfield/canfield.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  canfield/cfscores/cfscores.d
endif

canfield/cfscores/cfscores:	 canfield/cfscores/cfscores.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  cribbage/cards.d cribbage/crib.d cribbage/extern.d cribbage/instr.d cribbage/io.d cribbage/score.d cribbage/support.d
endif

cribbage/cribbage:	 cribbage/cards.o cribbage/crib.o cribbage/extern.o cribbage/instr.o cribbage/io.o cribbage/score.o cribbage/support.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  dab/algor.d dab/board.d dab/box.d dab/gamescreen.d dab/human.d dab/main.d dab/player.d dab/random.d dab/ttyscrn.d
endif

dab/dab:	 dab/algor.o dab/board.o dab/box.o dab/gamescreen.o dab/human.o dab/main.o dab/player.o dab/random.o dab/ttyscrn.o
	$(CXX) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  fish/fish.d
endif

fish/fish:	 fish/fish.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  gomoku/bdinit.d gomoku/bdisp.d gomoku/main.d gomoku/makemove.d gomoku/pickmove.d gomoku/stoc.d
endif

gomoku/gomoku:	 gomoku/bdinit.o gomoku/bdisp.o gomoku/main.o gomoku/makemove.o gomoku/pickmove.o gomoku/stoc.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  hack/alloc.d hack/hack.Decl.d hack/hack.apply.d hack/hack.bones.d hack/hack.d hack/hack.cmd.d hack/hack.do.d hack/hack.do_name.d hack/hack.do_wear.d hack/hack.dog.d hack/hack.eat.d hack/hack.end.d hack/hack.engrave.d hack/hack.fight.d hack/hack.invent.d hack/hack.ioctl.d hack/hack.lev.d hack/hack.main.d hack/hack.makemon.d hack/hack.mhitu.d hack/hack.mklev.d hack/hack.mkmaze.d hack/hack.mkobj.d hack/hack.mkshop.d hack/hack.mon.d hack/hack.monst.d hack/hack.o_init.d hack/hack.objnam.d hack/hack.options.d hack/hack.pager.d hack/hack.potion.d hack/hack.pri.d hack/hack.read.d hack/hack.rip.d hack/hack.rumors.d hack/hack.save.d hack/hack.search.d hack/hack.shk.d hack/hack.shknam.d hack/hack.steal.d hack/hack.termcap.d hack/hack.timeout.d hack/hack.topl.d hack/hack.track.d hack/hack.trap.d hack/hack.tty.d hack/hack.u_init.d hack/hack.unix.d hack/hack.vault.d hack/hack.version.d hack/hack.wield.d hack/hack.wizard.d hack/hack.worm.d hack/hack.worn.d hack/hack.zap.d hack/rnd.d
endif

hack/hack:	 hack/alloc.o hack/hack.Decl.o hack/hack.apply.o hack/hack.bones.o hack/hack.o hack/hack.cmd.o hack/hack.do.o hack/hack.do_name.o hack/hack.do_wear.o hack/hack.dog.o hack/hack.eat.o hack/hack.end.o hack/hack.engrave.o hack/hack.fight.o hack/hack.invent.o hack/hack.ioctl.o hack/hack.lev.o hack/hack.main.o hack/hack.makemon.o hack/hack.mhitu.o hack/hack.mklev.o hack/hack.mkmaze.o hack/hack.mkobj.o hack/hack.mkshop.o hack/hack.mon.o hack/hack.monst.o hack/hack.o_init.o hack/hack.objnam.o hack/hack.options.o hack/hack.pager.o hack/hack.potion.o hack/hack.pri.o hack/hack.read.o hack/hack.rip.o hack/hack.rumors.o hack/hack.save.o hack/hack.search.o hack/hack.shk.o hack/hack.shknam.o hack/hack.steal.o hack/hack.termcap.o hack/hack.timeout.o hack/hack.topl.o hack/hack.track.o hack/hack.trap.o hack/hack.tty.o hack/hack.u_init.o hack/hack.unix.o hack/hack.vault.o hack/hack.version.o hack/hack.wield.o hack/hack.wizard.o hack/hack.worm.o hack/hack.worn.o hack/hack.zap.o hack/rnd.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  hack/makedefs.d
endif

hack/makedefs:	 hack/makedefs.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  hangman/endgame.d hangman/extern.d hangman/getguess.d hangman/getword.d hangman/main.d hangman/playgame.d hangman/prdata.d hangman/prman.d hangman/prword.d hangman/setup.d
endif

hangman/hangman:	 hangman/endgame.o hangman/extern.o hangman/getguess.o hangman/getword.o hangman/main.o hangman/playgame.o hangman/prdata.o hangman/prman.o hangman/prword.o hangman/setup.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  hunt/hunt/connect.d hunt/hunt/hunt.d hunt/hunt/otto.d hunt/hunt/playit.d hunt/huntd/pathname.d
endif

hunt/hunt/hunt:	 hunt/hunt/connect.o hunt/hunt/hunt.o hunt/hunt/otto.o hunt/hunt/playit.o hunt/huntd/pathname.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  hunt/huntd/answer.d hunt/huntd/ctl.d hunt/huntd/ctl_transact.d hunt/huntd/draw.d hunt/huntd/driver.d hunt/huntd/execute.d hunt/huntd/expl.d hunt/huntd/extern.d hunt/huntd/faketalk.d hunt/huntd/get_names.d hunt/huntd/makemaze.d hunt/huntd/shots.d hunt/huntd/terminal.d
endif

hunt/huntd/huntd:	 hunt/huntd/answer.o hunt/huntd/ctl.o hunt/huntd/ctl_transact.o hunt/huntd/draw.o hunt/huntd/driver.o hunt/huntd/execute.o hunt/huntd/expl.o hunt/huntd/extern.o hunt/huntd/faketalk.o hunt/huntd/get_names.o hunt/huntd/makemaze.o hunt/huntd/pathname.o hunt/huntd/shots.o hunt/huntd/terminal.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  mille/comp.d mille/end.d mille/extern.d mille/init.d mille/mille.d mille/misc.d mille/move.d mille/print.d mille/roll.d mille/save.d mille/types.d mille/varpush.d
endif

mille/mille:	 mille/comp.o mille/end.o mille/extern.o mille/init.o mille/mille.o mille/misc.o mille/move.o mille/print.o mille/roll.o mille/save.o mille/types.o mille/varpush.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  monop/cards.d monop/execute.d monop/getinp.d monop/houses.d monop/jail.d monop/misc.d monop/monop.d monop/morg.d monop/print.d monop/prop.d monop/rent.d monop/roll.d monop/spec.d monop/trade.d
endif

monop/monop:	 monop/cards.o monop/execute.o monop/getinp.o monop/houses.o monop/jail.o monop/misc.o monop/monop.o monop/morg.o monop/print.o monop/prop.o monop/rent.o monop/roll.o monop/spec.o monop/trade.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  monop/initdeck.d
endif

monop/initdeck:	 monop/initdeck.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  morse/morse.d
endif

morse/morse:	 morse/morse.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  number/number.d
endif

number/number:	 number/number.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  phantasia/fight.d phantasia/gamesupport.d phantasia/interplayer.d phantasia/io.d phantasia/main.d phantasia/misc.d phantasia/phantglobs.d
endif

phantasia/phantasia:	 phantasia/fight.o phantasia/gamesupport.o phantasia/interplayer.o phantasia/io.o phantasia/main.o phantasia/misc.o phantasia/phantglobs.o
	$(CC) $(LDFLAGS) $^ -lm $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  phantasia/setup.d
endif

phantasia/setup:	 phantasia/phantglobs.o phantasia/setup.o
	$(CC) $(LDFLAGS) $^ -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  pig/pig.d
endif

pig/pig:	 pig/pig.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  pom/pom.d
endif

pom/pom:	 pom/pom.o
	$(CC) $(LDFLAGS) $^ -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  ppt/ppt.d
endif

ppt/ppt:	 ppt/ppt.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  primes/pattern.d primes/pr_tbl.d primes/primes.d
endif

primes/primes:	 primes/pattern.o primes/pr_tbl.o primes/primes.o
	$(CC) $(LDFLAGS) $^ -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  quiz/quiz.d quiz/rxp.d
endif

quiz/quiz:	 quiz/quiz.o quiz/rxp.o lib/fgetln.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  rain/rain.d
endif

rain/rain:	 rain/rain.o lib/getprogname.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  random/random.d
endif

random/random:	 random/random.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  robots/auto.d robots/extern.d robots/flush_in.d robots/init_field.d robots/main.d robots/make_level.d robots/move.d robots/move_robs.d robots/play_level.d robots/query.d robots/rnd_pos.d robots/score.d
endif

robots/robots:	 robots/auto.o robots/extern.o robots/flush_in.o robots/init_field.o robots/main.o robots/make_level.o robots/move.o robots/move_robs.o robots/play_level.o robots/query.o robots/rnd_pos.o robots/score.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  sail/assorted.d sail/game.d sail/globals.d sail/dr_1.d sail/dr_2.d sail/dr_3.d sail/dr_4.d sail/dr_5.d sail/dr_main.d sail/lo_main.d sail/main.d sail/misc.d sail/parties.d sail/pl_1.d sail/pl_2.d sail/pl_3.d sail/pl_4.d sail/pl_5.d sail/pl_6.d sail/pl_7.d sail/pl_main.d sail/sync.d sail/version.d
endif

sail/sail:	 sail/assorted.o sail/game.o sail/globals.o sail/dr_1.o sail/dr_2.o sail/dr_3.o sail/dr_4.o sail/dr_5.o sail/dr_main.o sail/lo_main.o sail/main.o sail/misc.o sail/parties.o sail/pl_1.o sail/pl_2.o sail/pl_3.o sail/pl_4.o sail/pl_5.o sail/pl_6.o sail/pl_7.o sail/pl_main.o sail/sync.o sail/version.o lib/strlcpy.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  snake/snake/snake.d
endif

snake/snake/snake:	 snake/snake/snake.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  snake/snscore/snscore.d
endif

snake/snscore/snscore:	 snake/snscore/snscore.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  tetris/input.d tetris/scores.d tetris/screen.d tetris/shapes.d tetris/tetris.d
endif

tetris/tetris:	 tetris/input.o tetris/scores.o tetris/screen.o tetris/shapes.o tetris/tetris.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  trek/abandon.d trek/attack.d trek/autover.d trek/capture.d trek/cgetc.d trek/check_out.d trek/checkcond.d trek/compkl.d trek/computer.d trek/damage.d trek/damaged.d trek/dcrept.d trek/destruct.d trek/dock.d trek/dumpgame.d trek/dumpme.d trek/dumpssradio.d trek/events.d trek/externs.d trek/getcodi.d trek/getpar.d trek/help.d trek/impulse.d trek/initquad.d trek/kill.d trek/klmove.d trek/lose.d trek/lrscan.d trek/main.d trek/move.d trek/nova.d trek/out.d trek/phaser.d trek/play.d trek/ram.d trek/ranf.d trek/rest.d trek/schedule.d trek/score.d trek/setup.d trek/setwarp.d trek/shield.d trek/snova.d trek/srscan.d trek/systemname.d trek/torped.d trek/visual.d trek/warp.d trek/win.d
endif

trek/trek:	 trek/abandon.o trek/attack.o trek/autover.o trek/capture.o trek/cgetc.o trek/check_out.o trek/checkcond.o trek/compkl.o trek/computer.o trek/damage.o trek/damaged.o trek/dcrept.o trek/destruct.o trek/dock.o trek/dumpgame.o trek/dumpme.o trek/dumpssradio.o trek/events.o trek/externs.o trek/getcodi.o trek/getpar.o trek/help.o trek/impulse.o trek/initquad.o trek/kill.o trek/klmove.o trek/lose.o trek/lrscan.o trek/main.o trek/move.o trek/nova.o trek/out.o trek/phaser.o trek/play.o trek/ram.o trek/ranf.o trek/rest.o trek/schedule.o trek/score.o trek/setup.o trek/setwarp.o trek/shield.o trek/snova.o trek/srscan.o trek/systemname.o trek/torped.o trek/visual.o trek/warp.o trek/win.o
	$(CC) $(LDFLAGS) $^ -lm $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  worm/worm.d
endif

worm/worm:	 worm/worm.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  worms/worms.d
endif

worms/worms:	 worms/worms.o
	$(CC) $(LDFLAGS) $^ $(NCURSES_LIB) $(BASE_LIBS) -o $@

ifneq ($(nodep),true)
include  wump/wump.d
endif

wump/wump:	 wump/wump.o
	$(CC) $(LDFLAGS) $^  $(BASE_LIBS) -o $@

.PHONY:	lib_clean
lib_clean:
	cd lib && rm -f -- a.out core *.o *.d *.i *.s *.d.tmp  $(lib_CLEANFILES)

.PHONY:	lib_install lib_install-strip lib_installdirs
lib_install:	lib_installdirs

lib_install-strip:
	$(MAKE) lib_install $(DEFS_TO_PASS_STRIP)

lib_installdirs:
	set -e; for d in $(lib_DIRS) /; do mkdir -p $(INSTALL_PREFIX)$$d; done

.PHONY:	clean mostlyclean distclean maintainer-clean
clean mostlyclean:	 lib_clean

distclean maintainer-clean:	clean
	rm -f subst.sed subst.rules
	rm -f test.out
	rm -f `cat substfiles substfiles2 |sed '/^#/d'`
	rm -f GNUmakefile
	rm -f a.out conftest.c include/bsd-games.h
	rm -f exec.libs.tmp exec.objs.tmp

.PHONY:	install install-strip

install:	 lib_install

install-strip:
	$(MAKE) install $(DEFS_TO_PASS_STRIP)

.PHONY: check test
check test:	all
	set -e; for f in tests/*.test; do echo $$f; $$f; done

# Standard GNU targets we don't support
.PHONY:	uninstall TAGS dist
uninstall TAGS dist:
	@echo "The GNU target \`$@' is not supported by this package." >&2; exit 1

# GNU targets that can do nothing
.PHONY:	info dvi
info dvi:
	@echo "This package comes with no Texinfo documentation."

