</$objtype/mkfile
LIB=../libgames.a$O
OFILES= fgetln.$O getloadavg.$O	getprogname.$O strlcpy.$O

HFILES=

</sys/src/cmd/mklib

CC=pcc
LD=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_RESEARCH_SOURCE -D_BSD_EXTENSION


nuke:V:
	mk clean
	rm -f $LIB
