</$objtype/mkfile

#depends that a dictionary as been installed in /lib/dict

TARG=hangman

OFILES= endgame.$O getguess.$O main.$O prdata.$O prword.$O\
	extern.$O getword.$O playgame.$O prman.$O setup.$O


HFILES=	hangman.h pathnames.h


BIN=/$objtype/bin/games

LIB=../libgames.a$O

</sys/src/cmd/mkone

CC=pcc
LD=pcc
CFLAGS=-c -I. -I.. -I../include \
	-D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -D_BSD_EXTENSION \
	-D_REENTRANT_SOURCE -D_RESEARCH_SOURCE 


%.$O: %.c
	$CC $CFLAGS $stem.c


install:V:
	cp $O.out $BIN/$TARG
	cp $TARG.6.in /sys/man/6/$TARG
	

clean:V:
    rm -f *.[$OS] [$OS].out

nuke:V:
	rm -f $BIN/$TARG
	rm -f /sys/man/6/$TARG
